name: lint-and-test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: self-hosted
    strategy:
      matrix:
        node: ["18"]
    name: Test on Node ${{ matrix.node }} # @TODO: add multiple ORM versions?
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Cache dependencies
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
        shell: bash

      - run: yarn lint
      - run: yarn build
      - run: yarn test