name: Publish to npm on new tag

on:
  # push:
  #   tags:
  #     - '*'
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.2.1

      - name: Setup
        uses: ./.github/actions/setup.yml

      - name: Print version
        run: echo ${{ steps.extract_version.outputs.version }}

      - name: Build
        run: yarn build

      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc
          yarn exec lerna publish --force-publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}