name: Publish to npm on new tag

on:
  # push:
  #   tags:
  #     - '*'
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.2.1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/Htdrogen'
          registry-url: https://npm.pkg.github.com/
          scope: '@abmf'

      - name: Cache dependencies
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
        shell: bash

      - name: Print version
        run: echo ${{ steps.extract_version.outputs.version }}

      - name: Build
        run: yarn build

      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc
          yarn exec lerna publish --force-publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}